provider1: zhipuai
model1: GLM-4-Flash 
provider2: zhipuai
model2: GLM-4-FlashX-250414

temperature: 0.2
R: 3
epsilon: 1
cooldown: 0.6

input: data/input_articles.jsonl
output: data/llm_scored_trust.jsonl
rubrics: data/rubric.txt
emotions: ["可信度感知",'共情关怀','值得性感知']
